In [1]:
import LoadBatches
from keras.models import load_model
from Models import FCN32, FCN8, SegNet, UNet
import glob
import cv2
import numpy as np
import random
import os

Using TensorFlow backend.


In [4]:
key = "unet"

method = {
    "fcn32": FCN32.FCN32,
    "fcn8": FCN8.FCN8,
    "segnet": SegNet.SegNet,
    'unet': UNet.UNet}

m = method[key](11, 320, 320)  # 有自定义层时，不能直接加载模型
m.load_weights("output/%s_model.h5" % key)



In [14]:
im = cv2.imread(r'.\dataset1\val\0016E5_07959.png', 1)
im.resize(320,320,3)

In [20]:
pr = m.predict(np.expand_dims(LoadBatches.getImageArr(im), 0))

In [17]:
im

array([[[ 38,  37,  37],
        [ 40,  38,  34],
        [ 39,  36,  32],
        ...,
        [255, 255, 203],
        [255, 255, 203],
        [255, 255, 203]],

       [[255, 255, 203],
        [255, 255, 203],
        [255, 255, 203],
        ...,
        [229, 231, 230],
        [243, 247, 247],
        [248, 254, 253]],

       [[225, 228, 224],
        [250, 251, 249],
        [253, 254, 252],
        ...,
        [ 79,  53,  49],
        [ 89,  70,  64],
        [106, 110, 102]],

       ...,

       [[ 29,  19,  17],
        [ 25,  17,  16],
        [ 27,  23,  21],
        ...,
        [ 36,  32,  31],
        [ 35,  31,  30],
        [ 42,  38,  37]],

       [[ 18,  16,  16],
        [ 15,  13,  13],
        [ 13,  11,  11],
        ...,
        [ 64,  53,  46],
        [ 63,  52,  45],
        [ 61,  53,  45]],

       [[ 62,  54,  46],
        [ 62,  54,  46],
        [ 63,  52,  45],
        ...,
        [ 26,  22,  21],
        [ 30,  27,  26],
        [ 33,  30,  29]]

In [21]:
pr

array([[[0.03589668, 0.21230118, 0.02089423, ..., 0.02468682,
         0.02089423, 0.02089423],
        [0.04505086, 0.15303648, 0.01401616, ..., 0.01401616,
         0.01401616, 0.01401616],
        [0.0329018 , 0.13849033, 0.01444415, ..., 0.01444415,
         0.01444415, 0.01444415],
        ...,
        [0.00329744, 0.01043028, 0.0032154 , ..., 0.00436597,
         0.0032154 , 0.0032154 ],
        [0.00321698, 0.01309258, 0.00321698, ..., 0.00475467,
         0.00321698, 0.00321698],
        [0.00955841, 0.04879943, 0.0087509 , ..., 0.01404939,
         0.0087509 , 0.0087509 ]]], dtype=float32)

In [23]:
input_height = 320
input_width = 320
pr = pr.reshape((input_height, input_width, 11)).argmax(axis=2)

In [24]:
pr

array([[5, 5, 5, ..., 5, 5, 5],
       [5, 5, 5, ..., 5, 5, 5],
       [5, 5, 5, ..., 5, 5, 5],
       ...,
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3]], dtype=int64)

In [25]:
im2 = cv2.imread(r'.\dataset1\valannot\0016E5_07959.png', 1)
im2.resize(320,320,3)

In [29]:
im2.shape

(320, 320, 3)

In [30]:
pr.shape

(320, 320)